import sys

replacements = [
    ("OpenWrt için Biyolojik Esinli, Refleksif QoS", "Biologically Inspired, Reflexive QoS for OpenWrt"),
    ("Danışman: ", "Advisor: "),
    ("Dr. Öğr. Üyesi Cihat Çetinkaya", "Asst. Prof. Dr. Cihat Çetinkaya"),
    ("Muğla Sıtkı Koçman Üniversitesi, Yazılım Mühendisliği", "Muğla Sıtkı Koçman University, Software Engineering"),
    ("Bitirme Projesi", "Graduation Project"),
    (">Motivasyon<", ">Motivation<"),
    (">Problem<", ">Problem<"), 
    ("Tek bir TCP akışı 20 Mbit/s'lik WAN bağlantısında 693 ms kuyruk gecikmesi oluşturuyor — oyun ve VoIP kullanılamaz hale geliyor.", "A single TCP flow causes 693 ms queue delay on a 20 Mbit/s WAN connection — making gaming and VoIP unusable."),
    ("Statik QoS:", "Static QoS:"),
    ("CAKE gibi modern AQM'ler bile DSCP etiketlerine dayanır; ISP'ler bu etiketleri siliyor ve tüm trafik aynı kuyruğa düşüyor.", "Even modern AQMs like CAKE rely on DSCP tags; ISPs strip these tags, causing all traffic to fall into the same queue."),
    ("Sabit bant genişliği:", "Fixed bandwidth:"),
    ("WAN hız sınırı kurulum sırasında bir kez ayarlanıyor; gerçek zamanlı tıkanıklık sinyallerine tepki verilemiyor.", "WAN speed limit is configured once during setup; it cannot react to real-time congestion signals."),
    (">Yaklaşım<", ">Approach<"),
    (">Çözüm<", ">Solution<"),
    ("Biyolojik İlham:", "Biological Inspiration:"),
    ("Mantar miselyum ağlarının adaptif besin dağıtım stratejisi → refleksif ağ kontrolü", "Adaptive nutrient distribution strategy of fungal mycelium networks → reflexive network control"),
    ("6-Sınıf Cihaz Personası:", "6-Class Device Persona:"),
    ("DPI veya ML olmadan, çip üzerinde &lt;1 μs karar", "On-chip &lt;1 μs decision without DPI or ML"),
    ("12-Sınıf Akış Taksonomisi:", "12-Class Flow Taxonomy:"),
    ("Pasif DNS, hedef port ipuçları ve davranışsal parmak izi birleştiren 3-sinyalli ağırlıklı oylama", "3-signal weighted voting combining passive DNS, target port hints, and behavioral fingerprinting"),
    ("Sıfır Flash Yazma:", "Zero Flash Writes:"),
    ("Tüm durum RAM'de tutuluyor — NAND flash ömrüne zarar yok (Xiaomi AX3000T'de canlı test edildi)", "All state is kept in RAM — no damage to NAND flash lifespan (live tested on Xiaomi AX3000T)"),
    (">Karşılaştırma<", ">Comparison<"),
    (">SİSTEM<", ">SYSTEM<"),
    (">GÖMÜLÜ<", ">EMBEDDED<"),
    (">OTOMATİK<", ">AUTOMATIC<"),
    (">ML YOK<", ">NO ML<"),
    (">DPI YOK<", ">NO DPI<"),
    (">ADAPTİF<", ">ADAPTIVE<"),
    (">Sistem Mimarisi<", ">System Architecture<"),
    (">1 Hz Refleksif Kontrol Döngüsü<", ">1 Hz Reflexive Control Loop<"),
    (">Ev Ağı (LAN)<", ">Home Network (LAN)<"),
    (">İnternet (WAN)<", ">Internet (WAN)<"),
    ("(Ortam Algılama)", "(Environment Sensing)"),
    ("ICMP çok-ping (RTT/jitter) · /proc/net/nf_conntrack · Netlink qdisc istatistikleri · Pasif DNS dinleme · BPF TC kancası pasif TCP RTT", "ICMP multi-ping (RTT/jitter) · /proc/net/nf_conntrack · Netlink qdisc stats · Passive DNS listening · BPF TC hook passive TCP RTT"),
    (">PASİF DNS<", ">PASSIVE DNS<"),
    ("(Besin Yoğunluğu Tespiti)", "(Nutrient Density Detection)"),
    ("EWMA düzleştirme · 6-sınıf cihaz personası (çoğunluk oylama) · 3-sinyalli akış sınıflandırıcı (DNS:0.6 + port:0.3 + davranış:0.1) · 2-tick kararlılık kapısı", "EWMA smoothing · 6-class device persona (majority voting) · 3-signal flow classifier (DNS:0.6 + port:0.3 + behavior:0.1) · 2-tick stability gate"),
    (">6-SINIF PERSONA<", ">6-CLASS PERSONA<"),
    (">12-SINIF SERVİS<", ">12-CLASS SERVICE<"),
    (">HİSTEREZ<", ">HYSTERESIS<"),
    ("(Ağ Adaptasyonu)", "(Network Adaptation)"),
    ("CAKE AQM hedef güncelleme (tc qdisc change) · iptables mangle DSCP kuralları · libnetfilter_conntrack CONNMARK push · nftables POSTROUTING DSCP geri yükleme · IFB ingress şekillendirme", "CAKE AQM target update (tc qdisc change) · iptables mangle DSCP rules · libnetfilter_conntrack CONNMARK push · nftables POSTROUTING DSCP restore · IFB ingress shaping"),
    ("(Dengeleme Refleksi)", "(Balancing Reflex)"),
    ("Geri besleme halkası (8 slot) · Adım boyutu adaptasyonu · Kayan EWMA taban çizgisi (β=0.01) · RTT otomatik düşürme/yeniden yükseltme merdiveni", "Feedback ring (8 slots) · Step size adaptation · Sliding EWMA baseline (β=0.01) · RTT auto-demote/promote ladder"),
    (">Sonraki döngüye geri besleme<", ">Feedback to next loop<"),
    (" — tüm durum RAM'de tutulur, sıfır flash yazma garantisi", " — all state kept in RAM, zero flash write guarantee"),
    (">DSCP → CAKE Tin Eşlemesi<", ">DSCP → CAKE Tin Mapping<"),
    (">Deney Sonuçları<", ">Experimental Results<"),
    (">Temel Metrikler<", ">Core Metrics<"),
    ("Oyun tin gecikmesi avantajı — Voice 225 μs vs Bulk 34.7 ms", "Gaming tin latency advantage — Voice 225 μs vs Bulk 34.7 ms"),
    ("DNS sinyali doğruluk artışı (pp) — 42.98% → 83.54% offline validasyon", "DNS signal accuracy increase (pp) — 42.98% → 83.54% offline validation"),
    ("In-vivo tin-matched doğruluğu (DNS aktif, 80-katalog, N=1,650 akış)", "In-vivo tin-matched accuracy (DNS active, 80-catalog, N=1,650 flows)"),
    ("aarch64 binary boyutu — sıfır flash yazma, musl libc statik bağlama", "aarch64 binary size — zero flash writes, musl libc static linking"),
    (">Faz 1 — İki Persona Doğrulaması<", ">Phase 1 — Dual Persona Validation<"),
    (">Oyun Gecikmesi Karşılaştırması (20 Mbit/s WAN)<", ">Gaming Latency Comparison (20 Mbit/s WAN)<"),
    (">FIFO (QoS yok)<", ">FIFO (No QoS)<"),
    (">CAKE (tek başına)<", ">CAKE (standalone)<"),
    (">Faz 2 — Altı Persona Karışık Yük<", ">Phase 2 — Six Persona Mixed Load<"),
    (">5 İstemci Altında Oyun Gecikmesi<", ">Gaming Latency under 5 Clients<"),
    (">CAKE (5 istemci)<", ">CAKE (5 clients)<"),
    (">MycoFlow (5 istemci)<", ">MycoFlow (5 clients)<"),
    (">In-Vivo DNS Validasyonu — Tin-Matched Doğruluk<", ">In-Vivo DNS Validation — Tin-Matched Accuracy<"),
    (">N=1,650 Akış · seed=42 · Unicauca Dataset<", ">N=1,650 Flows · seed=42 · Unicauca Dataset<"),
    (">DNS yok (port+davr.)<", ">No DNS (port+behav.)<"),
    (">DNS aktif (80-kat.)<", ">DNS active (80-cat.)<"),
    (">DNS aktif (585-kat.)<", ">DNS active (585-cat.)<"),
    (">Sistem Özellikleri<", ">System Specifications<"),
    (">Hedef donanım<", ">Target hardware<"),
    (">CPU kullanımı<", ">CPU usage<"),
    (">Binary boyutu<", ">Binary size<"),
    (">Test kapsamı<", ">Test coverage<"),
    (">Dağıtım<", ">Deployment<"),
    ("canlı AX3000T üzerinde", "on live AX3000T"),
    ("Sınırlama:", "Limitation:"),
    (" ECH/QUIC opak payload — pasif DNS veya port tabanlı sınıflandırma çalışmıyor; bu trafik ", " ECH/QUIC opaque payload — passive DNS or port-based classification fails; this traffic "),
    (" sınıfına düşüyor. DNS katalog kapsamı tin-matched doğruluğu doğrudan etkiliyor (80-kat. → 66.97%, 585-kat. → 70.41%). ISP bant genişliği değişikliklerinde UCI manuel güncelleme gereklidir.", " class. DNS catalog coverage directly impacts tin-matched accuracy (80-cat. → 66.97%, 585-cat. → 70.41%). Manual UCI update is required for ISP bandwidth changes."),
    ("Gelecek Çalışmalar:", "Future Work:"),
    (" QUIC/ECH trafikleri için eBPF tabanlı hafif akış-zamanlaması (flow-timing) analizi entegrasyonu planlanmaktadır.", " eBPF-based lightweight flow-timing analysis integration is planned for QUIC/ECH traffic."),
    ("Sonuç:", "Conclusion:"),
    (" MycoFlow, standart ev donanımlarında (ör. Xiaomi AX3000T) sıfır flaş yazma ve mikrosaniye altı karar mekanizmasıyla, biyolojik esinli refleksif ağ yönetiminin (miselyum ağı konsepti) yeni nesil yönlendiricilerde tam anlamıyla uygulanabilirliğini kanıtlamıştır.", " MycoFlow proves the full viability of biologically inspired reflexive network management (mycelium network concept) on standard home hardware (e.g. Xiaomi AX3000T) with zero flash writes and sub-microsecond decision making."),
    (">KAYNAKLAR<", ">REFERENCES<"),
    ("Muğla Sıtkı Koçman Üniversitesi &nbsp;·&nbsp; Yazılım Mühendisliği Bölümü &nbsp;·&nbsp; 2025–2026 Akademik Yılı Bitirme Projesi", "Muğla Sıtkı Koçman University &nbsp;·&nbsp; Software Engineering Department &nbsp;·&nbsp; 2025–2026 Academic Year Graduation Project"),
    (">REFLEKSİF KONTROL<", ">REFLEXIVE CONTROL<"),
    (">BİYOLOJİK ESİNLİ AĞ<", ">BIO-INSPIRED NETWORK<"),
    (">PASİF RTT<", ">PASSIVE RTT<"),
    (">Kaynak Kodu<", ">Source Code<")
]

with open('/home/baris/mycoflow-core/poster/poster.html', 'r', encoding='utf-8') as f:
    content = f.read()

for t_old, t_new in replacements:
    content = content.replace(t_old, t_new)

with open('/home/baris/mycoflow-core/poster/poster.html', 'w', encoding='utf-8') as f:
    f.write(content)
print("done")
